### ISSUE TITLE
When we call share option error comes title and app crashes

### ISSUE THREAD

**Issue by coolvasanth** [codebetterme/react-native-share#2]
Hi, I have used the same code as mentioned in the documentation, when I try to run the application I get a error screen with message title. 
My platform information:
Platform : Android
React Native version: 0.62

**Comment by mrminhhuy** [comment]
hi @coolvasanth 
i was fixed it in version 0.1.2, you can reinstall and try again.

**Comment by coolvasanth** [comment]
Sure, will try again and revert.
