### ISSUE TITLE
TypeError: null is not an object  (evaluating 'ShareImages.show')

### ISSUE THREAD

**Issue by sebastianknopp** [codebetterme/react-native-share#3]
Hey,

thanks a lot for this library. I followed the instructions but can't get it to work. 

My app crashes immediately on execution saying "TypeError: null is not an object  (evaluating 'ShareImages.show')". 

My IDE claims "Could not find a declaration file for module 'react-native-files-share'. "

Please find detailed screenshots attached.

Thanks in advance,

Sebastian
![Hine from IDE on missing declaration file](https://user-images.githubusercontent.com/7078641/87057739-8b8c2a80-c207-11ea-9fbf-f635f641f474.png)
![Error message on crash](https://user-images.githubusercontent.com/7078641/87057787-9a72dd00-c207-11ea-8c5e-aa6a2d8378d3.PNG)

**Comment by mrminhhuy** [comment]
@sebastianknopp Hi, i fixed it in version 0.1.3. You could upgrade and retry. Thanks so much

**Comment by mildfuzz** [comment]
I'm seeing this error on Android running 3.7.0

**Comment by mildfuzz** [comment]
I'm seeing this error on Android running 3.7.0

```
      const url = 'iVBORw0KGgoAAAANSUhEUgAA...iukxNVAAAAAElFTkSuQmCC'
      ShareImages.show({
        images: [url], // list images base64 or pdf base64
        exclude: [''],
      })
```


gives me:
```
[Mon Sep 28 2020 08:31:01.570]  WARN     Possible Unhandled Promise Rejection (id: 0):
TypeError: null is not an object (evaluating 'ShareImages.show')
```

and no share dialogue

**Comment by mrminhhuy** [comment]
hi @mildfuzz 
thanks for using. Could you provide react, react native info, also android version that you used?

**Comment by mildfuzz** [comment]
Sorry, updating to latest fixed this issue
